name: CI

on:
  pull_request: {}
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  lint-containerfile:
    name: Lint Containerfile
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

    - name: Run hadolint
      uses: hadolint/hadolint-action@2332a7b74a6de0dda2e2221d575162eba76ba5e5 # v3.3.0
      with:
        dockerfile: Containerfile
        ignore: DL3002

  lint-yaml:
    name: Lint YAML files
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

    - name: Install yamllint
      run: pip install yamllint==1.38.0

    - name: Run yamllint
      run: yamllint .tekton/ .github/ renovate.json
